### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by vitalisc** [martinmiglio/pymemuc#39]
I would like to inquire about the software you use to inspect Android app elements on MEmu. I have attempted various alternatives, such as UIAutomation Viewer, but it consistently displays errors.
thanks

**Comment by martinmiglio** [comment]
I am not quite sure what you're referring to, but pymemuc isn't aware of the UI elements on the emulator. This is unrelated to the project.

**Comment by martinmiglio** [comment]
see my response to #40, it might have some information you need... unless you've seen it already
