### ISSUE TITLE
help: finding UI elements using pymemuc and ADB

### ISSUE THREAD

**Issue by amclaire** [martinmiglio/pymemuc#40]
went through your documentation  and example usage, they are great but am looking for these two things 
1. how to perform a click on element using xpath ,css or id
2.how to find out if element Exist or find element

thanks

**Comment by martinmiglio** [comment]
android emulators do not expose UI elements in a manner which pymemuc could query them. i'm not sure this is even possible...

**Comment by martinmiglio** [comment]
Using the ADB shell, you can find UI elements in some applications, see these stackoverflow answers [here](https://stackoverflow.com/a/26589447) and [here](https://stackoverflow.com/a/50027374).

The ADB shell can be used through pymemuc by calling [`send_adb_command_vm`](https://pymemuc.martinmiglio.dev/en/latest/pymemuc.html#pymemuc.pymemuc.PyMemuc.send_adb_command_vm). Something like this:
```python
from pymemuc import PyMemuc

pmc = PyMemuc(debug=True)
MY_VM_INDEX = 0 # replace this with your target vm index

ui_dump = pmc.send_adb_command_vm(command="shell uiautomator dump", vm_index=MY_VM_INDEX)
print(ui_dump) # this will read out the xml ui dump, from which you might parse element positional info
```

Clicking can only be done through coordinates using the [adb input tap command](https://stackoverflow.com/a/5392547).

**Comment by amclaire** [comment]
ok thanks let me try it out
