### ISSUE TITLE
finding UI elements using pymemuc and ADB

### ISSUE THREAD

**Issue by amclaire** [martinmiglio/pymemuc#41]
i found this https://qxf2.com/blog/identify-ui-elements-mobile-apps/
 You said something about using coordinates 
 The shortcomings with this approach are

The coordinates differ for each device
Layout might change in an app update
Ads pop up from memu or the main app, can stop the coordinates
Xpath or id remains the best way to locate element on any app

my question is that is there no way  to make use of what we have in the url ablove 
Example:https://www.youtube.com/watch?v=sd0Cy1VYWzU

**Comment by martinmiglio** [comment]
why not use the appium package they mention? does it not do what you're looking for?

**Comment by martinmiglio** [comment]
[How to install python modules](https://docs.python.org/3/installing/index.html)

**Comment by amclaire** [comment]
do you have a solution for performing a tap?

**Comment by martinmiglio** [comment]
[pymemuc can send any ADB command](https://pymemuc.martinmiglio.dev/en/latest/pymemuc.html#pymemuc.pymemuc.PyMemuc.send_adb_command_vm) to MEmu emulators, including the ADB input tap command.
